### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by SunsgneDZ** [maltsugar/GYIntroductionView#1]
demo中测试example0方法时 滑动图片会造成图片卡顿
![image](https://user-images.githubusercontent.com/24729554/42300657-1b9981b6-8044-11e8-9a79-08151151d2e4.png)

**Comment by maltsugar** [comment]
兄弟，我试了 不卡顿啊，这个是collectionView做的，按理说也不存在性能问题。你试试换其他模拟器呢，我知道iPhone X的模拟器是会卡顿的，这个好像是xcode的问题，任何项目都一样

**Comment by maltsugar** [comment]
不好意思，改了下。我又仔细发现了确实会有问题。感谢提出，新版本已修复。 多谢🤝
